### ISSUE TITLE
It deserves more popularity

### ISSUE THREAD

**Issue by allenhwkim** [mattlewis92/create-plunker#1]
This is nice code. I really liked it.
I personally used it in my project, and it really works well; https://github.com/ng2-ui/map

What I recommend is to write more detailed explanation about how to use each function. 
More documentation will draw more attention from users, and I think this deserve it.

**Comment by mattlewis92** [comment]
I'm glad that you found this module helpful! I've added some jsdoc comments to each function which should automatically appear in intellisense if you're using TS, typedoc for creating a nice-ish ui of the methods + a link to the tests which shows some more example usage. Hope that helps! 😄
